version: '3'

services:

  app:
    build:
      context: ./node
    container_name: node-app
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - nodejsnet
    ports:
      - "3000:3000"

  webserver:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodejsnet

networks:
  nodejsnet:
    driver: bridge
