version: '3'

services:

  app:
    build:
      context: ./node
    container_name: node-app
    command: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - nodejsnet
    ports:
      - "3000:3000"
    depends_on:
      - db

  webserver:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodejsnet
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root

    networks:
      - nodejsnet

networks:
  nodejsnet:
    driver: bridge
