version: '3'

services:

  app:
    build:
      context: ./node
    container_name: node-app
    command: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes:
      - ./node/app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - nodejsnet
    ports:
      - "3000:3000"
    depends_on:
      - db

  webserver:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodejsnet
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root

    networks:
      - nodejsnet

networks:
  nodejsnet:
    driver: bridge
