FROM golang:1.24 as builder

WORKDIR /usr/src/app

RUN go mod init jeanmalves/fullcycle

COPY ./main.go .

RUN go build main.go


FROM scratch

WORKDIR /usr/src/app

COPY --from=builder usr/src/app/main .

CMD [ "./main" ]